spring:
  application:
    name: chat-with-docs
  datasource:
    url: jdbc:postgresql://pgvector:5432/chat-with-docs
    username: admin
    password: password
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
      index-type: hnsw
      distance-type: COSINE_DISTANCE
      dimensions: 1536
  docker:
    compose:
      lifecycle-management: start_only